name: LazyPaml
author: PEMapModder
version: 1.0.0
api: [1.5.0]
main: lazypaml\Registrator
load: STARTUP
permissions:
  lazypaml:
    description: parent node for all LazyPaml permissions. You are not recommended to modify me and my children nodes.
    default: false
    children:
      lazypaml.false:
        description: false permission node for LazyPamls. You are not recommended to modify me.
        default: false
      lazypaml.true:
        description: true permission node for LazyPamls. You are not recommended to modify me.
        default: true
      lazypaml.op:
        description: op-only permission node for LazyPamls. You are not recommended to modify me.
        default: op
      lazypaml.notop:
        description: non-op-only permission node for LazyPamls. You are not recommended to modify me.
        default: notop
